// export interface User {
//     userName: string;
      
//     password: string;
// }

// Generated by https://quicktype.io

export interface User {
    userName:   string;
    password:   string;
    token?:      string;
    activo?:     boolean;
    cod_clave?:  number;
    grupoClave?: GrupoClave;
}

export interface GrupoClave {
    cod_clave:       number;
    cod_funcionario: string;
    cod_grupo:       string;
    clave:           string;
    apoya_a:         string;
    ppp:             string;
    grupoAcceso:     GrupoAcceso;
}

export interface GrupoAcceso {
    cod_grupo:   string;
    descripcion: string;
}
